### PR TITLE
Dave/release automation

### PR DESCRIPTION
**Pull request by dave-smartystreets**
This change adds semver, changelog, and release automation

### CODE REVIEW

**Comment by dave-smartystreets** [comment]
@camiblanch, I added semver, changelog, and release automation capabilities to this project.  It is based off of these instructions: https://blog.logrocket.com/automatically-generate-and-release-a-changelog-with-node-js/

**Comment by dave-smartystreets** [comment]
@camiblanch, I just learned that `standard-version` has been deprecated.  Please pause on review until I'm done investigating an alternative called `release-please`

**Comment by camiblanch** [comment]
@dave-smartystreets Do we need versioning on this repo? I thought we only needed it on `smartystreets-javascript-sdk` and `smartystreets-javascript-sdk-utils`

**Comment by dave-smartystreets** [comment]
Yes, no versioning is necessary on this repo, but I didn't want to have
lots of extraneous commits and otherwise noise on our main project repo.
This felt like a good place to experiment and learn.

**Comment by camiblanch** [comment]
Oh I see! Okay carry on. I look forward to reviewing this. Let me know when it's ready

**Comment by dave-smartystreets** [comment]
Will do, thanks!

**Pull request closed without merging**
